# User config
author: "Kimnamsun"
tagline: ""
description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
keywords: "nsunny, Web Developer"
email: "kimnsunnie@gmail.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/kimnamsun"
notion: "https://www.notion.so/namsun-Kim-3e32988d63aa4845b131edb4fd522b6a"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed