# User config
author: "Kim namsun"
tagline: ""
description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
keywords: "nsunny, Web Developer"
email: "kimnsunnie@gmail.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/kimnamsun"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed