# Site settings
title: KIMNAMSUN
description: >
  Frontend Developer
author: Kimnamsun
email: kimnsunnie@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kimnamsun.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username: kimnamsun

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
  style: compressed
